class CreateMasters < ActiveRecord::Migration[5.0]
  def change
    create_table :masters do |t|
      t.string :a 
      t.string :b 
      t.string :c 
      t.string :d 
      t.string :e 
      t.string :f 
      t.string :g 
      t.string :h 
      t.string :i 
      t.string :j 
      t.string :k 
      t.string :l 
      t.string :m 
      t.string :n 
      t.string :o 
      t.string :p 
      t.string :q 
      t.string :r 
      t.string :s 
      t.string :t              
      t.string :u 
      t.string :v 
      t.string :w 
      t.string :x 
      t.string :y 
      t.string :z 
      t.string :aa 
      t.string :ab 
      t.string :ac 
      t.string :ad 
      t.string :ae 
      t.string :af 
      t.string :ag 
      t.string :ah 
      t.string :ai 
      t.string :aj 
      t.string :ak 
      t.string :al 
      t.string :am 
      t.string :an 
      t.string :ao 
      t.string :ap 
      t.string :aq 
      t.string :ar 
      t.string :as 
      t.string :at              
      t.string :au 
      t.string :av 
      t.string :aw 
      t.string :ax 
      t.string :ay 
      t.string :az     
      t.string :ba 
      t.string :bb 
      t.string :bc 
      t.string :bd 
      t.string :be 
      t.string :bf 
      t.string :bg 
      t.string :bh 
      t.string :bi 
      t.string :bj 
      t.string :bk 
      t.string :bl 
      t.string :bm 
      t.string :bn 
      t.string :bo 
      t.string :bp 
      t.string :bq 
      t.string :br 
      t.string :bs 
      t.string :bt              
      t.string :bu 
      t.string :bv 
      t.string :bw 
      t.string :bx 
      t.string :by 
      t.string :bz     
      t.string :ca 
      t.string :cb                              
      t.timestamps
    end
  end
end
